apiVersion: v1
kind: Secret
metadata:
  name: data-migration
  namespace: dataloader
stringData:
  bootstrap_server: "b-2.mskclusterapse1mg.bjzm1o.c2.kafka.ap-southeast-1.amazonaws.com:9094,b-3.mskclusterapse1mg.bjzm1o.c2.kafka.ap-southeast-1.amazonaws.com:9094,b-1.mskclusterapse1mg.bjzm1o.c2.kafka.ap-southeast-1.amazonaws.com:9094"
  security_protocol: "SSL"
  sasl_mechanism: "SCRAM-SHA-512"
  s3_bucket: "s3://699955796816-ap-southeast-1-gft-dm-uat-athena-queries"
  database_name: "uat_migrationdb"
  region_name: "ap-southeast-1"
  workgroup: "primary"
