version: "3.8"

services:
  glue5_jupyter:
    image: glue_v5_livy
    container_name: glue5_jupyter
    volumes:
      - ~/.aws:/home/hadoop/.aws
      - ./code/:/home/hadoop/workspace/
    command: pyspark
    stdin_open: true
    tty: true
